# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '15.PyQt5/PyQt54Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 242)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.txtSayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSayi1.setGeometry(QtCore.QRect(80, 20, 191, 32))
        self.txtSayi1.setObjectName("txtSayi1")
        self.txtSayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSayi2.setGeometry(QtCore.QRect(80, 60, 191, 32))
        self.txtSayi2.setObjectName("txtSayi2")
        self.btnTopla = QtWidgets.QPushButton(self.centralwidget)
        self.btnTopla.setGeometry(QtCore.QRect(20, 110, 121, 31))
        self.btnTopla.setObjectName("btnTopla")
        self.btnCikar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCikar.setGeometry(QtCore.QRect(150, 110, 121, 31))
        self.btnCikar.setObjectName("btnCikar")
        self.btnBol = QtWidgets.QPushButton(self.centralwidget)
        self.btnBol.setGeometry(QtCore.QRect(150, 150, 121, 31))
        self.btnBol.setObjectName("btnBol")
        self.btnCarp = QtWidgets.QPushButton(self.centralwidget)
        self.btnCarp.setGeometry(QtCore.QRect(20, 150, 121, 31))
        self.btnCarp.setObjectName("btnCarp")
        self.lbl_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(20, 190, 251, 21))
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 293, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sayı 1"))
        self.label_2.setText(_translate("MainWindow", "Sayı 2"))
        self.btnTopla.setText(_translate("MainWindow", "Toplama"))
        self.btnCikar.setText(_translate("MainWindow", "Çıkarma"))
        self.btnBol.setText(_translate("MainWindow", "Bölme"))
        self.btnCarp.setText(_translate("MainWindow", "Çarpma"))
        self.lbl_sonuc.setText(_translate("MainWindow", "Sonuç "))
